config/routes.rb
Rails.application.routes.draw do

  root 'public/homes#top'

  #管理者
  devise_for :admin, skip: [:passwords] ,controllers: {
    sessions: 'admin/sessions',
  }
  #会員
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: 'public/registrations',
    sessions: 'public/sessions',
  }
  namespace :admin do
    get 'admin/new', to: 'admin/sessions#new'
      resources :customers do
        
        collection do
          get 'customers/leave' => 'customers#leave'
          patch 'customers/out' => 'customers#out'
        end
      end
   
    resources :searches
      get "search" => "searches#search"
    resources :categories, only:[:index, :edit, :create, :update]
    resources :movies, only:[:show, :new, :index, :edit, :create, :update] do
    end
  end
  
  #genres
  namespace :public do
    resources :customers do
        collection do
          get 'customers/leave' => 'customers#leave'
          patch 'customers/out' => 'customers#out'
        end
    end
    get "movies_comment" => "movies_comment#index"
    resources :searches
      get "search" => "searches#search"
      resources :categories, only:[:index, :edit, :create, :update]
      resources :movies do
        resources :movies_comment
      end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/movie.rb
class Movie < ApplicationRecord
   belongs_to :customer,optional: true
   has_many :real_estate_comments, dependent: :destroy
   attachment :image
end

app/models/movie_comment.rb
class MovieComment < ApplicationRecord
  belongs_to :movie
  belongs_to :customer
  validates :rate, numericality: {
    less_than_or_equal_to: 5,
    greater_than_or_equal_to: 1}, presence: true
end

app/controllers/admin/confirmations_controller.rb
# frozen_string_literal: true

class Admin::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admin/movies_controller.rb
class Admin::MoviesController < ApplicationController
end

app/controllers/admin/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Admin::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/admin/passwords_controller.rb
# frozen_string_literal: true

class Admin::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admin/registrations_controller.rb
# frozen_string_literal: true

class Admin::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  
  protected
  def after_sign_in_path_for(resource)
    admin_movies_path
  end

  def after_sign_out_path_for(resource)
    new_admin_session_path
  end

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   protect_from_forgery with: :exception
  def after_sign_in_path_for(resource)
    public_customer_path(current_customer.id)
  end
  def after_sign_out_path_for(resource)
    root_path # ログアウト後に遷移するpathを設定
  end
  def require_login!
    if session[:customer_email].nil?
      redirect_to login_path
    end
  end
  Refile.secret_key = '9953169e74f1595b3dff1c45e9c8275784e7f1bf81d3fb38f0a4e321807531492c18d93cf192e217972898440fa8ddce9b06c1c7f2a934d2223aa13992e1dc26'
  # before_action :authenticate_customer!,except: [:top,:about]
  add_flash_types :success, :info, :warning, :danger
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,keys:[:email, :first_name, :last_name, :password, :password_confirmation, :first_name_kana, :last_name_kana, :sexuality, :age])
  end
end

app/helpers/admin/movies_helper.rb
module Admin::MoviesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/movies/new.html.erb
<div class = "contents">
  <div class='row'>
    <div class='col-md-9 offset-md-1'>
      <h3>映画を登録してください。</h3>
      <%= form_with model: @movie, url:public_movies_path, local: true do |f| %>
      <table border ="1" >
        <tr>
          <th>入力項目</th>
          <th>入力欄</th>
        </tr>
        <tr>
          <td> 
            <%= f.label :movie_name, "映画名" %>
          </td>
          <td>
            <%= f.text_area :movie_name, placeholder: "ここに映画名を入力します" %>
          </td>
        </tr>
        <tr>
          <td>
            画像選択
          </td>
          <td>
            <%= f.attachment_field :image %>
          </td>
        <tr></tr>
         
        </table>
        <%= f.submit "投稿する", class:"btn btn-success" %>
      </div>
        <% end %>
    </div>
</div>

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GoGocinema</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if controller.class.parent.name == "Admin" %>
      <%= render "admin/shared/header" %>
    <% else %>
      <%#= render "public/shared/header" %>
    <% end %>
    
    <%# if signed_in? && unchecked_notifications.any?  %>
      <i class="fa fa-circle" style="color: gold;"></i>
    <%# end %>
    
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
<script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    
    <%= yield %>
  </body>
    
    <footer class="mt-4">
     <%#= render "shared/footer" %>
    </footer>
    
</html>